package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mariane Todeschini
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public FrmMenu() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOS = new javax.swing.JButton();
        btnVeiculos = new javax.swing.JButton();
        btnRelatorioFinanceiro = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnRelatorioOS = new javax.swing.JButton();
        btnMecanicos = new javax.swing.JButton();
        btnRelarioComissoes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnServiços = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        btnOS.setText("OS");
        btnOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOSMousePressed(evt);
            }
        });

        btnVeiculos.setText("Veículos");
        btnVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVeiculosMousePressed(evt);
            }
        });

        btnRelatorioFinanceiro.setText("Relatório Financeiro");
        btnRelatorioFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRelatorioFinanceiroMousePressed(evt);
            }
        });

        btnProdutos.setText("Produtos");
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProdutosMousePressed(evt);
            }
        });

        btnRelatorioOS.setText("Relatório OS");
        btnRelatorioOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRelatorioOSMousePressed(evt);
            }
        });

        btnMecanicos.setText("Mecânicos");
        btnMecanicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMecanicosMousePressed(evt);
            }
        });

        btnRelarioComissoes.setText("Relatório Comissões");
        btnRelarioComissoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRelarioComissoesMousePressed(evt);
            }
        });

        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientesMousePressed(evt);
            }
        });

        btnUsuarios.setText("Usuários");
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuariosMousePressed(evt);
            }
        });

        btnServiços.setText("Serviços");
        btnServiços.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnServiçosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelatorioFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(btnRelatorioOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelarioComissoes, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelarioComissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMecanicos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMousePressed
        FrmCliente frmCliente = new FrmCliente();
        frmCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesMousePressed

    private void btnVeiculosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiculosMousePressed
        FrmVeiculo frmVeiculo = new FrmVeiculo();
        frmVeiculo.setVisible(true);
    }//GEN-LAST:event_btnVeiculosMousePressed

    private void btnProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMousePressed
        FrmProduto frmProduto = new FrmProduto();
        frmProduto.setVisible(true);
    }//GEN-LAST:event_btnProdutosMousePressed

    private void btnOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOSMousePressed
        FrmOrdemDeServiço frmOrdemDeServiço = new FrmOrdemDeServiço();
        frmOrdemDeServiço.setVisible(true);
    }//GEN-LAST:event_btnOSMousePressed

    private void btnUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMousePressed
        FrmUsuario frmUsuario = new FrmUsuario();
        frmUsuario.setVisible(true);
    }//GEN-LAST:event_btnUsuariosMousePressed

    private void btnServiçosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiçosMousePressed
        FrmServiço frmServiço = new FrmServiço();
        frmServiço.setVisible(true);
    }//GEN-LAST:event_btnServiçosMousePressed

    private void btnMecanicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMecanicosMousePressed
        FrmMecanico frmMecanico = new FrmMecanico();
        frmMecanico.setVisible(true);
    }//GEN-LAST:event_btnMecanicosMousePressed

    private void btnRelatorioOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioOSMousePressed
        FrmRelatorioOrdemDeServiço frmRelatorioOrdemDeServiço = new FrmRelatorioOrdemDeServiço();
        frmRelatorioOrdemDeServiço.setVisible(true);
    }//GEN-LAST:event_btnRelatorioOSMousePressed

    private void btnRelarioComissoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelarioComissoesMousePressed
        FrmRelatorioComissoes frmRelatorioComissoes = new FrmRelatorioComissoes();
        frmRelatorioComissoes.setVisible(true);
    }//GEN-LAST:event_btnRelarioComissoesMousePressed

    private void btnRelatorioFinanceiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioFinanceiroMousePressed
        FrmRelatorioFinanceiro frmRelatorioFinanceiro = new FrmRelatorioFinanceiro();
        frmRelatorioFinanceiro.setVisible(true);
    }//GEN-LAST:event_btnRelatorioFinanceiroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMecanicos;
    private javax.swing.JButton btnOS;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelarioComissoes;
    private javax.swing.JButton btnRelatorioFinanceiro;
    private javax.swing.JButton btnRelatorioOS;
    private javax.swing.JButton btnServiços;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVeiculos;
    // End of variables declaration//GEN-END:variables
}
